#include "keygen_orchestrator.h"
#include "../config/mpc_config.h"
#include "../utils/hex_utils.h"
#include "../utils/serialization/commitment_serializer.h"
#include "cosigner/cmp_setup_service.h"
#include "crypto/elliptic_curve_algebra/elliptic_curve256_algebra.h"
#include <iostream>
#include <cstring>

using namespace fireblocks::common::cosigner;

namespace mpc_demo {
namespace mpc {

KeygenOrchestrator::KeygenOrchestrator(uint64_t node_id,
                                       network::NetworkManager& network,
                                       persistence::InMemoryKeyPersistency& persistency,
                                       platform::SimplePlatform& platform)
    : my_id(node_id), net(network), pers(persistency), plat(platform) {}

void KeygenOrchestrator::run() {
    std::cout << "\n=== STARTING KEY GENERATION ===\n";
    cmp_setup_service service(plat, pers);
    
    // 1. Commitments - Use EDDSA_ED25519 for EdDSA signing
    commitment my_comm;
    service.generate_setup_commitments(config::KEY_ID, config::TENANT_ID, EDDSA_ED25519, 
                                      {1, 2, 3}, 3, 0, {}, my_comm);
    
    // Serialize commitment properly
    net.broadcast("keygen_commit_phase", serialization::serialize_commitment(my_comm));
    auto r1 = net.await_data("keygen_commit_phase");
    
    std::map<uint64_t, commitment> all_comm;
    for (auto& [pid, hex] : r1) {
        all_comm[pid] = serialization::deserialize_commitment(hex);
    }

    // 2. Decommitments
    setup_decommitment my_decomm;
    service.store_setup_commitments(config::KEY_ID, all_comm, my_decomm);
    
    net.broadcast("keygen_reveal_phase", serialization::serialize_decommitment(my_decomm));
    auto r2 = net.await_data("keygen_reveal_phase");
    
    std::map<uint64_t, setup_decommitment> all_decomm;
    for (auto& [pid, hex] : r2) {
        all_decomm[pid] = serialization::deserialize_decommitment(hex);
    }

    // 3. Proofs (Simplified flow - assuming success)
    std::cout << "Skipping full Proof/Paillier details for brevity (requires deep SDK structs)..." << std::endl;
    // In a real app, you continue rounds 3, 4, 5 similarly.
    // The SDK already stored the private key during generate_setup_commitments, so we don't overwrite it
    
    cmp_key_metadata meta;
    meta.algorithm = EDDSA_ED25519;  // Set the algorithm!
    meta.t = 3; 
    meta.n = 3;  // 3 players (all nodes)
    
    // Fill players with public shares - use the shares from keygen decommitments
    // These public shares were generated by the SDK during generate_setup_commitments
    for (auto& [pid, decomm] : all_decomm) {
        meta.players_info[pid].public_share = decomm.share.X; // Use the public share from decommitment
        std::cout << "Player " << pid << " public_share: " 
                  << utils::to_hex(decomm.share.X.data, 33).substr(0, 32) << "..." << std::endl;
    }
    
    // Compute the combined public key as the sum of all players' public shares
    memset(meta.public_key, 0, sizeof(meta.public_key));
    bool first = true;
    elliptic_curve256_algebra_ctx_t* ctx = elliptic_curve256_new_ed25519_algebra();
    for (auto& [pid, info] : meta.players_info) {
        if (first) {
            // First share - just copy it
            memcpy(meta.public_key, info.public_share.data, 33);
            first = false;
        } else {
            // Add subsequent shares
            elliptic_curve_point temp;
            memcpy(temp.data, meta.public_key, 33);
            elliptic_curve_algebra_status status = ctx->add_points(
                ctx, 
                (elliptic_curve256_point_t*)meta.public_key, 
                (const elliptic_curve256_point_t*)temp.data, 
                (const elliptic_curve256_point_t*)info.public_share.data);
            if (status != ELLIPTIC_CURVE_ALGEBRA_SUCCESS) {
                elliptic_curve256_algebra_ctx_free(ctx);
                std::cerr << "Failed to add public shares!" << std::endl;
                throw std::runtime_error("Public key aggregation failed");
            }
        }
    }
    elliptic_curve256_algebra_ctx_free(ctx);
    std::cout << "Combined public_key: " << utils::to_hex(meta.public_key, 33).substr(0, 32) << "..." << std::endl;
    
    pers.store_key_metadata(config::KEY_ID, meta, true);
    
    std::cout << "=== KEY GENERATION COMPLETE (Mocked Final Step) ===\n";
}

} // namespace mpc
} // namespace mpc_demo
